[workspace]

resolver = "2"

members = [
    "project_0",
    "project_1",
    "project_2",
    "project_3",
    "project_4",
    "project_5",
    "project_6",
    "project_7",
    "project_8",
    "project_9",
]