[package]
name = "code-crush"
description = "CodeCrush: Puzzle Play"
authors = ["Davide Ferrero"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.1"
queues = "1.1.0"
rand = "0.8.5"
